Fix "rotation" action is not shown problem and fix the problems of IndividualPickerActivityTest.
- Avoids the "rotation" action is not shown correctly when onCategoryLoaded() is called after onBottomActionBarReady().
- [Test case] Change the behavior of clicking the tile.
- [Test case] Remove the tests for rotation tile UI.
- [Test case] Change the trigger point of the daily rotation from the rotation tile to the rotation action.
- [Test case] Fix the RuntimeException below for testShowStartRotationDialog_WifiOnly_ClickOK_Fails_ShowsErrorDialog(), testStartRotation_WifiOnly_FailOnce_Retry(), and testStartRotation_WifiOnly_FailOnce_Retry_ShouldStillHaveWifiTurnedOff().

java.lang.RuntimeException: Waited for the root of the view hierarchy to have window focus and not request layout for 10 seconds. If you specified a non default root matcher, it may be picking a root that never takes focus.

Bug: 157259520
Test: adb shell am instrument -w -r    -e debug false -e class 'com.android.wallpaper.picker.individual.IndividualPickerActivityTest' com.google.android.apps.wallpaper.tests/androidx.test.runner.AndroidJUnitRunner
Change-Id: I14cf96e0a4a8b6ffef01b932d6cc4d29e267da7d
(cherry picked from commit 58e4a1c432abee924c6132c6807d8508b89ae052)